// <auto-generated />
namespace JavaScriptSerialization.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dd2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dd2));
        
        string IMigrationMetadata.Id
        {
            get { return "201304171523316_dd2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
